version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    parallelism: 1
    working_directory: ~/better-ethereum-blockies
    steps:
      - checkout
      - restore_cache:
          keys:
          - node-modules-{{ checksum "package.json" }}
          - node-modules-
      - run:
          name: "Installing modules"
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}
      - run:
          name: "Checking correct types"
          command: |
            mkdir -p reports/flow
            yarn flow:ci
      - run:
          name: "Linting code"
          command: yarn lint:ci
      - run:
          name: "Running unit tests"
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/jest-results.xml"
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - run:
          name: "Building library"
          command: yarn build:ci

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
